/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2018-01-16 06:07:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class book1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  \r\n");
      out.write(" <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>Booking Form - Room Booking Calendar</title>\r\n");
      out.write("\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-capable\" content=\"yes\"> \r\n");
      out.write("    \r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"css/bootstrap-responsive.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/font-awesome.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<!-- <link href=\"css/pages/book.css\" rel=\"stylesheet\" type=\"text/css\"> -->\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"sweet-alert.css\">\r\n");
      out.write(" <script src=\"js/sweet-alert.min.js\"></script>\r\n");
      out.write(" \r\n");
      out.write(" <script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>\r\n");
      out.write(" \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t $(document).ready(function () {\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t Date.prototype.toDateInputValue = (function() {\r\n");
      out.write("\t\t\t    var local = new Date(this);\r\n");
      out.write("\t\t\t    local.setMinutes(this.getMinutes() - this.getTimezoneOffset());\r\n");
      out.write("\t\t\t    return local.toJSON().slice(0,10);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t if(");
      out.print(request.getAttribute("booked"));
      out.write("==false)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\r\n");
      out.write("\t\t\t sweetAlertInitialize();\r\n");
      out.write("\t\t\t sweetAlert(\"Oops...!\", \"Timing & dates are clashing.\\nCheck the dashboard for status and availability\");\r\n");
      out.write("\t\t\t \t/* alert(\"Booking cannot be done..!!\\nTiming & dates are clashing.\\nCheck the dashboard for status\");  */\r\n");
      out.write("\t\t/* \t \talert(\"firstname:\"+name);   */\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t //alert(new Date().toDateInputValue());\r\n");
      out.write("\t\t $('#start_date').prop(\"min\",new Date().toDateInputValue());\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t\t//alert(\"Inside onload\");\r\n");
      out.write("\t\t //Check date and time ranges conditions\r\n");
      out.write("\t\t $(\"#start_date\").blur(function (){\r\n");
      out.write("//\t\t\t\talert($(\"#start_date\").val());\r\n");
      out.write("\t\t\t\t$(\"#end_date\").prop(\"min\",$(\"#start_date\").val());\r\n");
      out.write("\t//\t\t\talert($(\"#end_date\"));\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t $(\"[name=start_time]\").blur(function(){\r\n");
      out.write("\t\t\t//\talert($(\"[name=start_time]\").val());\r\n");
      out.write("\t\t\t\tvar temp=$(\"[name=start_time]\").val();\r\n");
      out.write("\t\t//\t\talert(temp);\r\n");
      out.write("\t\t\t\t$(\"[name=end_time]\").prop(\"min\",temp);\r\n");
      out.write("\t\t\t\t//alert($(\"[name=end_time]\"));\r\n");
      out.write("\t\t });\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t //fullday checkbox code\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#fullDay\").click(function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\tif($(this).is(':checked'))\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t//\t\t\talert(\"inside checked\");\r\n");
      out.write("\t\t\t\t\t\t\t\t $(\"[name=start_time]\").val(\"09:00\");  // checked\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"[name=start_time]\").attr(\"readonly\", \"true\");\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"[name=end_time]\").val(\"18:00\");  // checked\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"[name=end_time]\").attr(\"readonly\", \"true\");\r\n");
      out.write("\t\t\t\t\t\t\t\t//$(\"#checkbox1\").attr(\"disabled\", \"disabled\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t//\talert(\"inside UNchecked\");\r\n");
      out.write("\t\t\t\t\t$(\"[name=start_time]\").removeAttr(\"readonly\");\r\n");
      out.write("\t\t\t\t\t$(\"[name=end_time]\").removeAttr(\"readonly\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif($(\"#fullDay\").is(':checked'))\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t//alert(\"Is checked function\");\r\n");
      out.write("\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"[name=start_time]\").attr(\"readonly\", \"true\");\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"[name=start_time]\").val(\"09:00\");  // checked\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"[name=end_time]\").attr(\"readonly\", \"true\");\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"[name=end_time]\").val(\"18:00\");  // checked\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t//$(\"#checkbox1\").attr(\"disabled\", \"disabled\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t$(\"[name=start_time]\").removeAttr(\"readonly\");\r\n");
      out.write("\t\t\t\t\t$(\"[name=end_time]\").removeAttr(\"readonly\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t \r\n");
      out.write("\t \r\n");
      out.write(" $.ajax(\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\t\t\t\t\turl:\"display_location.jsp\",\r\n");
      out.write("\t\t\t\t\t\t\tdata:{loc:$(this).val()},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\tsuccess:function(data)\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t//alert('hi');\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#location').html(data);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t/* for(var i=0;i<data.length;i++)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\talert(data[i]);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#roomid\").append(\"<option>\"+data[i]+\"</option>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t} */\r\n");
      out.write("\t\t\t\t \t\t\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\terror:function(data,status,error)\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t//\talert(data[1]);\r\n");
      out.write("\t\t\t\t\t\t\t//alert(\"Error occured in ajax\"+error+\":\"+status);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}); \r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t$('select#location').change(function(event) {\r\n");
      out.write("\t\t//alert($(this).val());\r\n");
      out.write("        var loc = $(this).val();\r\n");
      out.write("        /* $.getJSON('display_room.jsp',{selectlocation: $(this).val(), ajax: 'true'}, function() {\r\n");
      out.write("         alert('hi');\r\n");
      out.write("        var select1 = $('select#roomid');\r\n");
      out.write("       // select1.find('option').remove();\r\n");
      out.write("          $.each(response, function(index, value) {\r\n");
      out.write("          $('<option>').val(value).text(value).appendTo(select1);\r\n");
      out.write("      });\r\n");
      out.write("        }); */\r\n");
      out.write("        \r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("   $.ajax(\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\t\t\t\t\t\turl:\"display_room.jsp\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tdata:{loc:$(this).val()},\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess:function(data)\r\n");
      out.write("\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t//\t\t\t\t\t\talert('hi');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#roomid').html(data);\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t/* for(var i=0;i<data.length;i++)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talert(data[i]);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#roomid\").append(\"<option>\"+data[i]+\"</option>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t} */\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t \t},\r\n");
      out.write("\t\t\t\t\t\t\terror:function(data,status,error)\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\talert(data[1]);\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"Error occured in ajax\"+error+\":\"+status);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("    \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"navbar navbar-fixed-top\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"navbar-inner\">\r\n");
      out.write("\t\t<div class=\"left\">\r\n");
      out.write("\t\t\t\t<img alt=\"\" src=\"PSLLogo.jpg\" width=\"70px\" height=\"70px\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<a class=\"btn btn-navbar\" data-toggle=\"collapse\" data-target=\".nav-collapse\">\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<a class=\"brand\" href=\"adminUser.jsp\">\r\n");
      out.write("\t\t\t\tRoom Booking Calendar\t\t\t\t\r\n");
      out.write("\t\t\t</a>\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"nav-collapse\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav pull-right\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li class=\"\">\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a href=\"adminUser.jsp\" class=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"icon-chevron-left\"></i>\r\n");
      out.write("\t\t\t\t\t\t\tBack to Homepage\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div><!--/.nav-collapse -->\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t</div> <!-- /container -->\r\n");
      out.write("\t\t<div class=\"right\">\r\n");
      out.write("\t\t<img alt=\"\" src=\"kc-logo-header (1).png\" width=\"70px\" height=\"70px\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div> <!-- /navbar-inner -->\r\n");
      out.write("\t\r\n");
      out.write("</div> <!-- /navbar -->\r\n");
      out.write("\r\n");
      out.write("<div  style=\"width: 50px; height: 50px;\"  > </div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"account-container register\"  align=\"center\" >\r\n");
      out.write("\t\r\n");
      out.write("<div class=\"content clearfix\" style=\"width: 380px; height: 650px; border: solid\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<form action=\"BookRoomController\"  method=\"post\">\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("<div class=\"login-fields\">\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("<h1>Book Room</h1>\t\t\t\r\n");
      out.write("\t\t<br>\t\t\r\n");
      out.write("\t<br>\t\t\t\r\n");


Long userid=(Long)session.getAttribute("userid");
String firstname=(String)session.getAttribute("firstname");


      out.write("\t\t\t\r\n");
      out.write("\t<table>\r\n");
      out.write("<tr>\r\n");
      out.write("\r\n");
      out.write("<td>\r\n");
      out.write("<label for=\"emp_id\">User Id </label></td><td><input type=\"text\" id=\"emp_id\" value=\"");
      out.print(userid);
      out.write("\" name=\"employeeid\" required/></td>\r\n");
      out.write("</tr>\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("\r\n");
      out.write("<label for=\"emp_id\">Owner Name  </label></td><td><input type=\"text\" id=\"emp_id\" name=\"empName\" value=\"");
      out.print(firstname);
      out.write("\" required/></td>\r\n");
      out.write("</tr>\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("<tr><td>\r\n");
      out.write("<label for=\"room_id\">Location Name  </label></td><td><select name=\"location\" id=\"location\" required>\r\n");
      out.write("</select></td>\r\n");
      out.write("</tr>\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("<tr><td>\r\n");
      out.write("<label for=\"roomid\">Room Name </label></td><td><select name=\"roomName\" id=\"roomid\" required>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</select>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<tr><td>\r\n");
      out.write("<label for=\"start_date\">Start Date </label></td><td><input type=\"date\" id=\"start_date\" name=\"sDate\" required></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td>\r\n");
      out.write("<label for=\"end_date\">End Date </label></td><td><input type=\"date\" id=\"end_date\" name=\"eDate\" required></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td>\r\n");
      out.write("<label for=\"training_type\" >Training Type</label>\r\n");
      out.write("</td><td>\r\n");
      out.write("<select name=\"training_type\">\r\n");
      out.write("\t<option>ELTP</option>\r\n");
      out.write("\t<option>RBT</option>\r\n");
      out.write("\t<option>SLT</option>\r\n");
      out.write("</select></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr><td>\r\n");
      out.write("<label for=\"training_name\">Training Name </label></td><td><input type=\"text\" id=\"training_name\" name=\"training_name\" required></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Full Day Booking</td><td><input type=\"checkbox\" id=\"fullDay\" checked=\"checked\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("<label for=\"start_time\">Start Time </label></td><td>\r\n");
      out.write("\r\n");
      out.write("<input type=time id=\"timeStart\" name=\"start_time\" min=9:00 max=19:00 step=900 required></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><label for=\"end_time\">End Time </label></td><td><input type=\"time\" id=\"timeEnd\" name=\"end_time\" min=9:00 max=19:00 step=900 required></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div> <!-- /login-fields -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"login-actions\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<br>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<button class=\"button btn btn-primary btn-large\">Book</button>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div> <!-- .actions -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div> <!-- /content -->\r\n");
      out.write("\t\r\n");
      out.write("</div> <!-- /account-container -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Text Under Box -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/signin.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write(" </html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
