/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2018-01-16 06:07:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class recurrenceForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  \r\n");
      out.write(" <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>Signup - Room Booking Calendar</title>\r\n");
      out.write("\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-capable\" content=\"yes\"> \r\n");
      out.write("    \r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"css/bootstrap-responsive.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/font-awesome.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"css/pages/signin.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write(" <link rel=\"stylesheet\" type=\"text/css\" href=\"sweet-alert.css\">\r\n");
      out.write(" <script src=\"js/sweet-alert.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.10.2.js\"></script>\r\n");
      out.write("  \t<script src=\"//code.jquery.com/ui/1.11.2/jquery-ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tDate.prototype.toDateInputValue = (function() {\r\n");
      out.write("\t    var local = new Date(this);\r\n");
      out.write("\t    local.setMinutes(this.getMinutes() - this.getTimezoneOffset());\r\n");
      out.write("\t    return local.toJSON().slice(0,10);\r\n");
      out.write("\t});\r\n");
      out.write("\t  if(");
      out.print(request.getAttribute("booked"));
      out.write("==false)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t  sweetAlertInitialize();\r\n");
      out.write("\t\t\t sweetAlert(\"Oops...!\", \"Timing & dates are clashing.\\nCheck the dashboard for status and availability\");\r\n");
      out.write("\t\t \t/* alert(\"Booking cannot be done..!!\\nTiming & dates are clashing.\\nCheck the dashboard for status\");  */\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t}  \r\n");
      out.write("\t $('#start').prop(\"min\",new Date().toDateInputValue());\t\r\n");
      out.write("\t\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t $(\"#fullDay\").click(function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($(this).is(':checked'))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t//\t\t\talert(\"inside checked\");\r\n");
      out.write("\t\t\t\t\t\t $(\"[name=stime]\").val(\"09:00\");  // checked\r\n");
      out.write("\t\t\t\t\t\t$(\"[name=stime]\").attr(\"readonly\", \"true\");\r\n");
      out.write("\t\t\t\t\t\t$(\"[name=etime]\").val(\"18:00\");  // checked\r\n");
      out.write("\t\t\t\t\t\t$(\"[name=etime]\").attr(\"readonly\", \"true\");\r\n");
      out.write("\t\t\t\t\t\t//$(\"#checkbox1\").attr(\"disabled\", \"disabled\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t//\talert(\"inside UNchecked\");\r\n");
      out.write("\t\t\t$(\"[name=stime]\").removeAttr(\"readonly\");\r\n");
      out.write("\t\t\t$(\"[name=etime]\").removeAttr(\"readonly\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($(\"#fullDay\").is(':checked'))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t//alert(\"Is checked function\");\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t$(\"[name=stime]\").attr(\"readonly\", \"true\");\r\n");
      out.write("\t\t\t\t\t\t$(\"[name=stime]\").val(\"09:00\");  // checked\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"[name=etime]\").attr(\"readonly\", \"true\");\r\n");
      out.write("\t\t\t\t\t\t$(\"[name=etime]\").val(\"18:00\");  // checked\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t//$(\"#checkbox1\").attr(\"disabled\", \"disabled\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$(\"[name=stime]\").removeAttr(\"readonly\");\r\n");
      out.write("\t\t\t$(\"[name=etime]\").removeAttr(\"readonly\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("//end of code for fuulday\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t $(\":radio\").click(function () {\r\n");
      out.write("\t\t \r\n");
      out.write("\t// alert(\"Inside Radio click\");\r\n");
      out.write("\t\t    var inputValue = $(this).val();\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    if(inputValue!=\"End by\")\r\n");
      out.write("\t\t    \t{\r\n");
      out.write("\t\t  //  \talert(\"input\"+inputValue);\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t    \t$(\"#end\").attr(\"disabled\", \"disabled\");\r\n");
      out.write("\t\t    \t}\r\n");
      out.write("\t\t    else\r\n");
      out.write("\t\t    \t{\r\n");
      out.write("\t\t    //\talert(\"input\"+inputValue);\r\n");
      out.write("\t\t    \t$(\"#end\").removeAttr(\"disabled\");;\r\n");
      out.write("\t\t    \t}\r\n");
      out.write("\t });\r\n");
      out.write("\t \r\n");
      out.write("\t\t//alert(\"Inside onload\");\r\n");
      out.write("\t //Check date and time ranges conditions\r\n");
      out.write("\t $(\"#start\").blur(function (){\r\n");
      out.write("//\t\t\talert($(\"#start_date\").val());\r\n");
      out.write("\t\t\t$(\"#end\").prop(\"min\",$(\"#start\").val());\r\n");
      out.write("//\t\t\talert($(\"#end_date\"));\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t $(\"#starttime\").blur(function(){\r\n");
      out.write("\t\t//\talert($(\"[name=start_time]\").val());\r\n");
      out.write("\t\t\tvar temp=$(\"#starttime\").val();\r\n");
      out.write("\t//\t\talert(temp);\r\n");
      out.write("\t\t\t$(\"#endtime\").prop(\"min\",temp);\r\n");
      out.write("\t\t\t//alert($(\"[name=end_time]\"));\r\n");
      out.write("\t });\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tgetLocation();\r\n");
      out.write("\t$('select#location').change(function(event) {\r\n");
      out.write("\t\t//alert($(this).val());\r\n");
      out.write("        var loc = $(this).val();\r\n");
      out.write("       \r\n");
      out.write("        \r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("   $.ajax(\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\t\t\t\t\t\turl:\"display_room.jsp\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tdata:{loc:$(this).val()},\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess:function(data)\r\n");
      out.write("\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t//alert('hi');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#roomid').html(data);\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t/* for(var i=0;i<data.length;i++)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talert(data[i]);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#roomid\").append(\"<option>\"+data[i]+\"</option>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t} */\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t \t},\r\n");
      out.write("\t\t\t\t\t\t\terror:function(data,status,error)\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\talert(data[1]);\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"Error occured in ajax\"+error+\":\"+status);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("}); \r\n");
      out.write("\r\n");
      out.write("function getLocation()\r\n");
      out.write("{/* \r\n");
      out.write("\t $.ajax({\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t url:\"demo_test.txt\",\r\n");
      out.write("\t\t success:function(result){\r\n");
      out.write("\t    \t\t$(\"#div1\").html(result);}\r\n");
      out.write("\t }\r\n");
      out.write("\t ); */\r\n");
      out.write("\t//alert(\"In get Location\");\r\n");
      out.write("\t$.ajax(\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttype:\"GET\",\r\n");
      out.write("\t\t\t\turl:\"display_location.jsp\",\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\tsuccess:function(data)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$('#location').html(data);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror:function(data,status,error)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(data[1]);\r\n");
      out.write("\t\t\t\talert(\"Error occured in ajax\"+error+\":\"+status);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"navbar navbar-fixed-top\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"navbar-inner\">\r\n");
      out.write("\t\t<div class=\"left\">\r\n");
      out.write("\t\t\t\t<img alt=\"\" src=\"PSLLogo.jpg\" width=\"70px\" height=\"70px\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<a class=\"btn btn-navbar\" data-toggle=\"collapse\" data-target=\".nav-collapse\">\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<a class=\"brand\" href=\"index.html\">\r\n");
      out.write("\t\t\t\tRoom Booking Calendar\t\t\t\t\r\n");
      out.write("\t\t\t</a>\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"nav-collapse\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav pull-right\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li class=\"\">\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a href=\"adminUser.jsp\" class=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"icon-chevron-left\"></i>\r\n");
      out.write("\t\t\t\t\t\t\tBack to Homepage\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div><!--/.nav-collapse -->\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t</div> <!-- /container -->\r\n");
      out.write("\t\t<div class=\"right\">\r\n");
      out.write("\t\t<img alt=\"\" src=\"kc-logo-header (1).png\" width=\"70px\" height=\"70px\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div> <!-- /navbar-inner -->\r\n");
      out.write("\t\r\n");
      out.write("</div> <!-- /navbar -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"account-container register\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"content clearfix\">\r\n");
      out.write("\t\t<form action=\"ReccurrenceController\" method=\"post\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("Location Name </td><td>\r\n");
      out.write("<select name=\"location\" id=\"location\">\r\n");
      out.write("\r\n");
      out.write("</select>\t\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("<label for=\"roomid\">Room Name  </label></td><td>\r\n");
      out.write("<select name=\"roomid\" id=\"roomid\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</select></td>\r\n");
      out.write("</tr>\t\t\t\r\n");
      out.write("<tr><td>\r\n");
      out.write("<label for=\"training_type\" >Training Type</label></td>\r\n");
      out.write("<td>\r\n");
      out.write("<select name=\"training_type\">\r\n");
      out.write("\t<option>ELTP</option>\r\n");
      out.write("\t<option>RBT</option>\r\n");
      out.write("\t<option>SLT</option>\r\n");
      out.write("</select></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td>\r\n");
      out.write("<label for=\"training_name\">Training Name </label></td><td><input type=\"text\" id=\"training_name\" name=\"training_name\" required></td></tr>\r\n");
      out.write("\r\n");
      out.write("<tr><td>\r\n");
      out.write("\t\t\t<p><b>Appointment time:</b></p></td></tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("<td>Full Day Booking</td><td><input type=\"checkbox\" id=\"fullDay\" checked=\"checked\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\t\t\t<tr><td>\r\n");
      out.write("\t      \t\t\t\t<h3> StartTime </h3></td><td>\t<input type=\"time\" id=\"starttime\" name=\"stime\" required></td></tr>\r\n");
      out.write("\t  \t\t\t\t\t<tr><td><h3> EndTime </h3></td><td>\t<input type=\"time\" id=\"endtime\" name=\"etime\" required></td></tr>\r\n");
      out.write("\t  \t\t\t\t\t</table>\r\n");
      out.write("\t  \t\t\t\t<!-- \t<h3>Duration</h3>\t<input type=\"text\" id=\"duration\"> -->\r\n");
      out.write("\t  \t\t\t\t\t<p><h3>Recurrence pattern</h3></p>\r\n");
      out.write("\t  \t\t\t\t\t<table id=\"recurrence\">\r\n");
      out.write("\t   \t\t\t\t\t\t<tr>\r\n");
      out.write("\t  \t\t\t\t\t\t<td>\r\n");
      out.write("\t  \t\t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\t<div class=\"recur\">\r\n");
      out.write("\t  \t\t\t\t\t\t<table id=\"numOfRecur\">\r\n");
      out.write("<!-- \t  \t\t\t\t\t\t<tr><td><b>Daily  </b></td><td><input type=\"radio\" name=\"recur\" value=\"Daily\"></td></tr>\r\n");
      out.write(" -->\t  \t\t\t\t\t\t<tr><td><b>Weekly</b></td><td><input type=\"radio\" name=\"recur\" value=\"Weekly\" required></td></tr>\r\n");
      out.write("\t  \t\t\t\t\t\t<tr><td><b>Monthly</b></td><td><input type=\"radio\" name=\"recur\" value=\"Monthly\" required></td></tr>\r\n");
      out.write("<!-- \t  \t\t\t\t\t\t<tr><td><b>Yearly  </b></td><td><input type=\"radio\" name=\"recur\" value=\"Yearly\"></td></tr>\t\r\n");
      out.write(" -->\t  \t\t\t\t\t\t</table>\r\n");
      out.write("\t  \t\t\t\t\t\t</div>\r\n");
      out.write("\t  \t\t\t\t\t\t</td>\r\n");
      out.write("\t  \t\t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\t</tr>\r\n");
      out.write("\t  \t\t\t\t\t</table>\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t<h3>Range of Recurrence</h3>\r\n");
      out.write("\t  \t\t\t\t\t<table>\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t<tr><td><b>Start : </b><input id=\"start\" type=\"date\" style=\"width: 120px\" name=\"sdate\" required></td></tr>\r\n");
      out.write("\t  \t\t\t\t\t<tr><td><input type=\"radio\" name=\"range\" value=\"No end date\" required><b>No end date</b></td></tr>\r\n");
      out.write("\t  \t\t\t\t\t<tr><td><input type=\"radio\" name=\"range\" value=\"End after\" required><b>End after : </b><input type=\"number\" id=\"occurrences\" style=\"width: 50px\" name=\"count\" min=\"1\" value=\"1\"> Occurrences</td></tr>\r\n");
      out.write("\t  \t\t\t\t\t<tr><td><input id=\"endBy\" type=\"radio\" name=\"range\" value=\"End by\" required><b>End by :</b><input type=\"date\" id=\"end\" style=\"width: 120px\" name=\"edate\"></td></tr>\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t</table>\r\n");
      out.write("\t  \t\t\t\t\t<button class=\"button btn btn-primary btn-large\" style=\"float:center;\" name=\"click\" value=\"OK\">OK</button>\r\n");
      out.write("\t  \t\t\t\t\t<a href=\"adminUser.jsp\" class=\"button btn btn-primary btn-large\" style=\"float:center;\">Cancel</a>\r\n");
      out.write("\t  \t\t\t\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t</div> <!-- /content -->\r\n");
      out.write("\t\r\n");
      out.write("</div> <!-- /account-container -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Text Under Box -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/signin.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write(" </html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
